# Generated by Django 2.0.5 on 2018-05-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='Testing Description', max_length=255),
            preserve_default=False,
        ),
    ]
